version: "3"

services:
  stone:
    init: true
    image: ghcr.io/ba-st/gs64-rowan:v3.7.0
    environment:
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - ./conf/:/opt/gemstone/conf/
      - ./locks/:/opt/gemstone/locks/
      - ./logs/:/opt/gemstone/logs/
      - ./projects/:/opt/gemstone/projects/
      - ~/.ssh/:/home/gemstone/.ssh/:ro
#     - ./your-keyfile.key:/opt/gemstone/product/sys/gemstone.key:ro
  gem:
    init: true
    depends_on:
      stone:
        condition: service_started
    image: ghcr.io/ba-st/gs64-gem:v3.7.0
    environment:
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - ./gem-conf/:/opt/gemstone/conf/
      - ./gem-logs/:/opt/gemstone/logs/
