version: "3"

services:
  stone:
    init: true
    network_mode: host
    build:
      context: ../source
      target: docker-gs64-rowan
      args:
        GS_VERSION: 3.7.0
    environment:
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - ./conf/:/opt/gemstone/conf/
      - ./locks/:/opt/gemstone/locks/
      - ./logs/:/opt/gemstone/logs/
      - ./projects/:/opt/gemstone/projects/
      - ~/.ssh/:/home/gemstone/.ssh/:ro
  gem:
    init: true
    network_mode: host
    depends_on:
      stone:
        condition: service_started
    build:
      context: ../source
      target: docker-gs64-gem
      args:
        GS_VERSION: 3.7.0
    environment:
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - ./gem-conf/:/opt/gemstone/conf/
      - ./gem-locks/:/opt/gemstone/locks/
      - ./gem-logs/:/opt/gemstone/logs/
