version: "3"

services:
  stone:
    init: true
    network_mode: host
    build:
      context: ../source
      target: docker-gs64-rowan
      args:
        GS_VERSION: 3.7.0
    cap_add:
      - CAP_SYS_RESOURCE
    environment:
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - ./conf/:/opt/gemstone/conf/
      - ./locks/:/opt/gemstone/locks/
      - ./logs/:/opt/gemstone/logs/
      - ./projects/:/opt/gemstone/projects/
      - ~/.ssh/:/home/gemstone/.ssh/:ro
